# Generated by Django 2.1.5 on 2020-07-07 18:12

import books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='library_item',
            fields=[
                ('library_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('copies', models.IntegerField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('pdf', models.FileField(default='string', upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='PersonExtend',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key='True', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('blacklisted', models.BooleanField(default='False')),
                ('fine', models.IntegerField(null='True')),
                ('checkoutdate', models.DateField(default=django.utils.timezone.now)),
                ('returndate', models.DateField(default=books.models.return_date_time)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('Book_Aur_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.library_item')),
                ('A_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='book_collection',
            fields=[
                ('library_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.library_item')),
                ('edition', models.IntegerField()),
                ('book_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='journal',
            fields=[
                ('library_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.library_item')),
                ('volume', models.IntegerField()),
                ('journal_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='magazine',
            fields=[
                ('library_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.library_item')),
                ('publish_date', models.DateField()),
                ('mag_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='library_item',
            name='pub_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.Publisher'),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('Book_Aur_ID', 'A_name')},
        ),
    ]
