# Generated by Django 2.1.5 on 2020-07-01 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('borrower_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('blacklisted', models.BooleanField()),
                ('academics', models.BooleanField()),
                ('fine', models.IntegerField()),
                ('b_rank', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='library_item',
            fields=[
                ('library_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('copies', models.IntegerField()),
                ('Image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('Book_Aur_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.library_item')),
                ('A_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('Book_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.library_item')),
                ('edition', models.DecimalField(decimal_places=5, max_digits=5)),
                ('book_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Borrows',
            fields=[
                ('Borrows_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.library_item')),
                ('returndate', models.DateField()),
                ('checkoutdate', models.DateField()),
                ('BID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Borrower')),
            ],
        ),
        migrations.CreateModel(
            name='journal',
            fields=[
                ('Jour_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.library_item')),
                ('volume', models.DecimalField(decimal_places=5, max_digits=5)),
                ('journal_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='magazine',
            fields=[
                ('Mag_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.library_item')),
                ('publish_date', models.DateField()),
                ('mag_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='library_item',
            name='pub_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.Publisher'),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('Book_Aur_ID', 'A_name')},
        ),
        migrations.AlterUniqueTogether(
            name='borrows',
            unique_together={('Borrows_ID', 'BID')},
        ),
    ]
