# Generated by Django 2.1.5 on 2020-07-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personextend',
            name='check',
            field=models.BooleanField(default='False'),
        ),
    ]
