# Generated by Django 2.1.5 on 2020-07-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_collection',
            old_name='library_Id',
            new_name='book_Id',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='library_Id',
            new_name='journal_Id',
        ),
        migrations.RenameField(
            model_name='magazine',
            old_name='library_Id',
            new_name='magazine_Id',
        ),
    ]
