# Generated by Django 2.1.5 on 2020-07-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_collection',
            name='edition',
            field=models.IntegerField(null='True'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_number',
            field=models.IntegerField(null='True'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='volume',
            field=models.IntegerField(null='True'),
        ),
    ]
