# Generated by Django 2.1.5 on 2020-07-02 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Book_Aur_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.library_item'),
        ),
        migrations.AlterField(
            model_name='books',
            name='edition',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='journal',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
