# Generated by Django 2.1.5 on 2020-07-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200702_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='book_collection',
        ),
    ]
