# Generated by Django 2.1.5 on 2020-07-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_personextend_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personextend',
            name='check',
        ),
    ]
